Create handle errors function #24
superhealthyminds/healthyminds pull request #27
Opened 2018-01-20 11:24 UTC by idantb101

in the process of creating a handler for the errors, I found out my refactoring of the queries was crashing the app in case of error because I was accessing res.row which means undefined.nothing.
there for I changed the queries, I added an error handler and handled all errors. close 24.

2018-01-21 09:28 UTC, Amirk390 submitted a review, later dismissed
Nice job :+1: 
Looks good

2018-01-21 09:54 UTC, NickP123 submitted a review, later dismissed

2018-01-21 10:20 UTC, NickP123 submitted a review, later dismissed

2018-01-21 10:20 UTC, Amirk390 submitted a review, later dismissed

2018-01-21 13:23 UTC, claireinez commented on src/app.js
> +/* eslint-disable */
I think you need to add the following to your `.eslintrc`:
```
  globals: {
    next: true // defined by express
  }
```

2018-01-21 20:55 UTC, NickP123 submitted a review, later dismissed

2018-01-21 20:57 UTC, Amirk390 submitted a review, later dismissed

2018-01-22 08:42 UTC, claireinez requested changes
Can you please fix spelling of the word "query" throughout? @Amirk390 and @NickP123 can you please review for spelling before assigning back to me?

2018-01-22 10:33 UTC, closed without merging